Songy.Admin/Controllers/CategoryController.cs
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class CategoryController : ApplicationBaseController
    {
        private CategoryService _service;

        ResponseModel<object> mResult;

        public CategoryController()
        {
            _service = new CategoryService();
        }

        public ActionResult Index()
        {
            IQueryable<AdminCategoryModel> objCategories = _service.GetAllCategory_IQueryable();
            return View(objCategories);
        }

        public ActionResult Add()
        {
            AdminCategoryModel model = new AdminCategoryModel();
            List<CategoryLanguageModel> CategoryLanguages = new List<CategoryLanguageModel>();
            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                Language = Language.English,
                LanguageName = Language.English.ToString(),
            });

            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                Language = Language.Arbic,
                LanguageName = Language.Arbic.ToString(),
            });

            model.Categorylanguagemodellist = CategoryLanguages;
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseIconCategory != null)
                {
                    Stream inStream = model.FileBaseIconCategory.InputStream;
                    Image PostedImage = Image.FromStream(inStream);

                    string ogFileName = model.FileBaseIconCategory.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseIconCategory.SaveAs(Path.Combine(GlobalConfig.CategoryIconPath, thisFileName));
                    model.IconName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");

            }
            return View("AddorUpdate", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            AdminCategoryModel model = await _service.GetCategoryDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseIconCategory != null)
                {
                    Stream inStream = model.FileBaseIconCategory.InputStream;
                    Image PostedImage = Image.FromStream(inStream);

                    string ogFileName = model.FileBaseIconCategory.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseIconCategory.SaveAs(Path.Combine(GlobalConfig.CategoryIconPath, thisFileName));
                    model.IconName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            mResult = await _service.DeleteCategory(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CheckExistingTitle()
        {
            bool IsExist = true;

            if (Request.Form[0] != null)
            {
                string Name = Request.Form[0];
                long CategoryId = Convert.ToInt64(Request.Form[1]);
                IsExist = _service.IsTitleExist(Name, CategoryId);
            }

            return Json(!IsExist);
        }
    }
}

Songy.Admin/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    [AllowAnonymous]
    public class ErrorController : Controller
    {
        public ActionResult Index(int errorCode, string errorTitle, string errorDescription)
        {
            ViewBag.errorCode = errorCode;
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();
        }
        public ActionResult NotFound()
        {
            return View();
        }
        public ActionResult BadRequest(string errorTitle, string errorDescription)
        {
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();

        }
        public ActionResult ServerError(string errorTitle, string errorDescription)
        {
            ViewBag.errorTitle = errorTitle;
            ViewBag.errorDescription = errorDescription;
            return View();
        }
        public ActionResult Unauthorized()
        {
            return View();
        }
        public ActionResult InvalidAccess()
        {
            return View();
        }
    }
}

Songy.Admin/Controllers/SongsController.cs
using Microsoft.AspNet.Identity;
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class SongsController : ApplicationBaseController
    {
        private SongsService _service;

        ResponseModel<object> mResult;

        public SongsController()
        {
            _service = new SongsService();
        }

        public ActionResult Index()
        {
            IQueryable<SongsViewModel> objSongs = _service.GetIQueryableSongs();
            return View(objSongs);
        }

        public async Task<ActionResult> Add()
        {
            SongsAddUpdateModel model = new SongsAddUpdateModel();
            BindList();
            return View("AddorUpdate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(SongsAddUpdateModel model)
        {
          
            if (ModelState.IsValid)
            {
                if (model.FileBaseSongs != null)
                {
                    string ogFileName = model.FileBaseSongs.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseSongs.SaveAs(Path.Combine(GlobalConfig.SongsPath, thisFileName));
                    model.FileName = thisFileName;
                }
                model.UserId = User.Identity.GetUserId();
                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");

            }
            BindList();
            return View("AddorUpdate", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            SongsAddUpdateModel mResult = await _service.GetSongsDetail(id);
            BindList(mResult.CategoryId);
            if (mResult == null)
                return RedirectToActionPermanent("Index");
            return View("AddorUpdate", mResult);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(SongsAddUpdateModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseSongs != null)
                {
                    string ogFileName = model.FileBaseSongs.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseSongs.SaveAs(Path.Combine(GlobalConfig.SongsPath, thisFileName));
                    model.FileName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            BindList();
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubCategory(int CategoryId)
        {

            using (SubCategoryService service = new SubCategoryService())
            {
                List<SubCategoryDropdownModel> Subcategories = (from x in service.GetSubCategoryDropdown(CategoryId)
                                                                select new SubCategoryDropdownModel
                                                                {
                                                                    Id = x.Id,
                                                                    Name = x.Name
                                                                }).ToList();
                return Json(Subcategories, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Songy.Admin/Controllers/UserController.cs
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class UserController : Controller
    {

        private UserService _service;
        public UserController()
        {
            _service = new UserService();
        }

        public ActionResult Index()
        {
            return View(_service.getAllUsers_IQueryable());
        }

        [HttpPost]
        public JsonResult ActiveToggle(string Id)
        {
            ResponseModel<bool> mResult = _service.ActiveToggle(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(string Id)
        {
            ResponseModel<object> mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> ForgotPasswordByAdmin(string Id)
        {
            ResponseModel<object> mResult = await _service.ForgotPasswordByAdmin(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Songy.Admin/Controllers/UtilityController.cs
using Microsoft.AspNet.Identity;
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class UtilityController : ApplicationBaseController
    {
        private readonly UtilityService _service;
        public UtilityController()
        {

            _service = new UtilityService();
        }
        public ActionResult Terms()
        {
            UtilityModel model = _service.TermsCondition();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Terms(UtilityModel model)
        {
            int id = await _service.UpdateTermsConditions(model);
            if (id < 1)
            {
                OnBindMessage(AlertStatus.Danger, "Failed to update terms and conditions!");
                ModelState.AddModelError("", "Failed to update terms and conditions!");
            }
            else
            {
                OnBindMessage(AlertStatus.Success, "Terms and conditions updated successfully.");

            }
            return RedirectToAction("Terms");
        }

        public ActionResult AboutUs()
        {
            UtilityModel model = _service.About();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> AboutUs(UtilityModel model)
        {
            int id = await _service.Updateabout(model);
            if (id < 1)
            {
                OnBindMessage(AlertStatus.Danger, "Failed to update AboutUs!");
                ModelState.AddModelError("", "Failed to update AboutUs!");
            }
            else
            {
                OnBindMessage(AlertStatus.Success, "AboutUs updated successfully.");
            }
            return RedirectToAction("AboutUs");
        }

        [HttpPost]
        public JsonResult UploadCropImage(SaveImageModel model)
        {
            string imageName = Guid.NewGuid().ToString() + "." + model.extension;
            string filePath = Path.Combine(model.saveFilePath, imageName);
            ResponseModel<object> mResult = Utilities.SaveCropImage(model.imgBase64String, filePath, model.extension);
            mResult.Result = imageName;

            if (!string.IsNullOrEmpty(model.previousImageName))
            {
                string ExistFilePath = Path.Combine(model.saveFilePath, model.previousImageName);
                if (System.IO.File.Exists(ExistFilePath))
                {
                    System.IO.File.Delete(ExistFilePath);
                }
            }

            return Json(mResult);
        }

        public ActionResult Notification()
        {
            BindPlatform();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Notification(NotificationSendModel model)
        {
            model.SenderID = User.Identity.GetUserId();
            NotificationService service = new NotificationService();
            ResponseModel<object> mResult = await service.NotificationSend(model);
            OnBindMessage(mResult.Status, mResult.Message);
            //if (mResult.Status == ResponseStatus.Success)
            return RedirectToAction("Index", "Home");
        }
    }
}

Songy.Admin/Views/Shared/_Alert.cshtml
@{ AlertModel alertModel = TempData["alertModel"] as AlertModel;
    if (alertModel != null)
    {
        if (!string.IsNullOrEmpty(alertModel.alertMessage))
        {
            <section id="solid-alerts">
                <div class="alert bg-@alertModel.alertStatus.ToString() alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <span id="message">@alertModel.alertMessage</span>
                </div>
            </section>
        }
    }
    else
    {
        <section id="solid-alerts" style="display:none">
            <div class="alert alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <span id="message"></span>
            </div>
        </section>
    }
}

Songy.Admin/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Songy.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    AlertModel alertModel = TempData["alertModel"] as AlertModel;
    int status = -1;
    string message = null;
    if (alertModel != null)
    {
        status = (int)alertModel.alertStatus;
        message = alertModel.alertMessage;
    }
}
<html lang="en" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-w idth, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>@ViewBag.Title -@GlobalConfig.ProjectName</title>
    <link rel="apple-touch-icon" sizes="57x57" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-57x57.png")">
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-60x60.png")">
    <link rel="apple-touch-icon" sizes="72x72" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-72x72.png")">
    <link rel="apple-touch-icon" sizes="76x76" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-76x76.png")">
    <link rel="apple-touch-icon" sizes="114x114" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-114x114.png")">
    <link rel="apple-touch-icon" sizes="120x120" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-120x120.png")">
    <link rel="apple-touch-icon" sizes="144x144" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-144x144.png")">
    <link rel="apple-touch-icon" sizes="152x152" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-152x152.png")">
    <link rel="apple-touch-icon" sizes="180x180" href="@Url.Content("~/Files/DefaultImages/favicon/apple-icon-180x180.png")">
    <link rel="icon" type="image/png" sizes="192x192" href="@Url.Content("~/Files/DefaultImages/favicon/android-icon-192x192.png")">
    <link rel="icon" type="image/png" sizes="32x32" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-32x32.png")">
    <link rel="icon" type="image/png" sizes="96x96" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-96x96.png")">
    <link rel="icon" type="image/png" sizes="16x16" href="@Url.Content("~/Files/DefaultImages/favicon/favicon-16x16.png")">
    <link rel="manifest" href="@Url.Content("~/Files/DefaultImages/favicon/manifest.json")">
    <meta name="msapplication-TileColor" content="#005893">
    <meta name="msapplication-TileImage" content="@Url.Content("~/Files/DefaultImages/favicon/ms-icon-144x144.png")">
    <meta name="theme-color" content="#005893">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    @Styles.Render("~/css/bundles")
    @Styles.Render("~/css/menu")
    @Scripts.Render("~/jQuery/bundles")
    @Styles.Render("~/css/zoom")
    <script src="~/Content/Plugins/zoom/zoom.js"></script>
    <link href="~/Content/Plugins/zoom/zoom.css" rel="stylesheet" />
</head>
<body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns fixed-navbar" id="body">
    <!-- navbar-fixed-top-->
    <nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav">
                    <li class="nav-item mobile-menu hidden-md-up float-xs-left">
                        <a class="nav-link nav-menu-main menu-toggle hidden-xs">
                            <i class="icon-menu5 font-large-1"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","Home")" class="navbar-brand nav-link">
                            <img alt="@GlobalConfig.ProjectName" src="@Url.Content("~/Files/DefaultImages/logo.png")" class="brand-logo"
                                 data-expand="@Url.Content("~/Files/DefaultImages/logo.png")"
                                 data-collapse="@Url.Content("~/Files/DefaultImages/small-logo.png")">
                        </a>
                    </li>
                    <li class="nav-item hidden-md-up float-xs-right">
                        <a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container">
                            <i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-container content container-fluid">
                <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
                    <ul class="nav navbar-nav">
                        <li class="nav-item hidden-sm-down">
                            <a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5"></i></a>
                        </li>
                        <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>
                    </ul>
                    <ul class="nav navbar-nav float-xs-right">
                        <li class="dropdown dropdown-user nav-item">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                                <span class="avatar avatar-online">
                                    <img src="@Url.Content("~/Files/DefaultImages/admin_avtar.png")" alt="avatar"><i></i>
                                </span>
                                <span class="user-name">@ViewBag.FullName</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="@Url.Action("changepassword", "Account")" class="dropdown-item"><i class="icon-head"></i> change password</a>
                                <div class="dropdown-divider"></div>
                                <a href="@Url.Action("Logout","Account")" class="dropdown-item"><i class="icon-power3"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- main menu-->
    <div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
        <div class="main-menu-content">
            <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
                <li class="nav-item" id="liHome">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="icon-home3"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" id="liTerms">
                    <a href="@Url.Action("Index", "User")">
                        <i class="icon-user"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">Users</span>
                    </a>
                </li>
                <li class="nav-item" id="liCategory">
                    <a href="@Url.Action("Index", "Category")">
                        <i class="icon-calendar5"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Category</span>
                    </a>
                </li>
                <li class="nav-item" id="liSubCategory">
                    <a href="@Url.Action("Index", "SubCategory")">
                        <i class="icon-sitemap"></i>
                        <span data-i18n="nav.dash.main" class="menu-title">Sub Category</span>
                    </a>
                </li>
                <li class="nav-item" id="liSongs">
                    <a href="@Url.Action("Index", "Songs")">
                        <i class="icon-music"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">Songs</span>
                    </a>
                </li>
                <li class="nav-item has-sub">
                    <a href="javascript:;">
                        <i class="icon-music2"></i>
                        <span data-i18n="nav.menu_levels.main" class="menu-title">Requested Songs</span>
                    </a>
                    <ul class="menu-content" style="">
                        <li class="nav-item" id="liUploaded">
                            <a href="@Url.Action("Uploaded", "RequestedSong")">
                                <i class="icon-music3"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Uploaded</span>
                            </a>
                        </li>
                        <li class="nav-item" id="liPending">
                            <a href="@Url.Action("Pending", "RequestedSong")">
                                <i class="icon-music3"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Pending</span>
                            </a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item" id="liContactUs">
                    <a href="@Url.Action("Index", "ContactUs")">
                        <i class="icon-ios-contact"></i>
                        <span data-i18n="nav.templates.main" class="menu-title">Contact Us</span>
                    </a>
                </li>
                <li class="nav-item has-sub">
                    <a href="javascript:;">
                        <i class="icon-gears"></i>
                        <span data-i18n="nav.menu_levels.main" class="menu-title">Settings</span>
                    </a>
                    <ul class="menu-content" style="">
                        <li class="nav-item" id="liAppSettings">
                            <a href="@Url.Action("Index", "AppSettings")">
                                <i class="icon-gear"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">App Settings</span>
                            </a>
                        </li>
                        <li class="nav-item" id="liNotification">
                            <a href="@Url.Action("Notification", "Utility")">
                                <i class="icon-notification"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Send notification</span>
                            </a>
                        </li>
                        <li class="nav-item" id="liAbout">
                            <a href="@Url.Action("AboutUs", "Utility")">
                                <i class="icon-information"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">About US</span>
                            </a>
                        </li>

                        <li class="nav-item" id="liTerms">
                            <a href="@Url.Action("Terms", "Utility")">
                                <i class="icon-gears"></i>
                                <span data-i18n="nav.templates.main" class="menu-title">Terms</span>
                            </a>
                        </li>

                    </ul>
                </li>

            </ul>
        </div>
    </div>
    <!-- / main menu-->

    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer footer-static footer-light navbar-border">
        <p class="clearfix text-muted text-sm-center mb-0 px-2">
            <span class="float-md-left d-xs-block d-md-inline-block">
            </span>
            <span class="float-md-right d-xs-block d-md-inline-block">
                Copyright  &copy; @DateTime.Now.Year
                <a href="#" target="_blank" class="text-bold-800 grey darken-2">@GlobalConfig.ProjectName</a>, All rights reserved.
            </span>
        </p>
    </footer>

    @Scripts.Render("~/jQuery/core")
    @Scripts.Render("~/jQuery/ui")
    @Scripts.Render("~/jQuery/zoom")
    @RenderSection("scripts", required: false)
    <script>
        //$(function () {
        //    $('img').attr('data-action', 'zoom');
        //});
        var status =@status;
        if(status==0){
            toastr.error('@message', 'Error !');
        }
        else if(status==1){
            toastr.success('@message', 'Success.');
        }
        else if(status==2){
            toastr.info('@message', 'Info.');
        }
        else if(status==3){
            toastr.warning('@message', 'Warning !');
        }
        else if(status==4){
            toastr.info('@message', 'Message.');
        }

    </script>
</body>
</html>