Songy.Admin/Controllers/SettingsController.cs
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class SettingsController : ApplicationBaseController
    {

    }
}

Songy.Admin/Views/Settings/About.cshtml
@model UtilityModel
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/summernote")
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">About Us</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        @using (Html.BeginForm("TermsPost", "Settings", FormMethod.Post, new { @id = "frmTerms", @class = "form-horizontal" }))
                        {
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-11">
                                        @Html.TextAreaFor(x => x.Description)
                                        @Html.ValidationMessageFor(x => x.Description)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <input type="submit" class="btn btn-md btn-primary" value="Save" />
                                        <a href="@Url.Action("Index")" class="btn btn-md btn-grey">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/summernote")

    <script type="text/javascript">
        ActiveMenu("About")
        $(function () {
            $('#Description').summernote({
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: false,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                ],
            });
        });
    </script>
}

Songy.Admin/Views/Settings/Terms.cshtml
@model UtilityModel
@{
    ViewBag.Title = "Terms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/summernote")
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">Terms & Conditions</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        @using (Html.BeginForm("TermsPost", "Settings", FormMethod.Post, new { @id = "frmTerms", @class = "form-horizontal" }))
                        {
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-11">
                                        @Html.TextAreaFor(x => x.Description)
                                        @Html.ValidationMessageFor(x => x.Description)
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <input type="submit" class="btn btn-md btn-primary" value="Save" />
                                        <a href="@Url.Action("Index")" class="btn btn-md btn-grey">
                                            Cancel
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/summernote")

    <script type="text/javascript">
        ActiveMenu("Terms")
        $(function () {
            $('#Description').summernote({
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: false,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                ],
            });
        });
    </script>
}