Songy.Admin/Controllers/CategoryController.cs
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class CategoryController : ApplicationBaseController
    {
        private CategoryService _service;

        ResponseModel<object> mResult;

        public CategoryController()
        {
            _service = new CategoryService();
        }

        public ActionResult Index()
        {
            IQueryable<AdminCategoryModel> objCategories = _service.GetAllCategory_IQueryable();
            return View(objCategories);
        }

        public ActionResult Add()
        {
            AdminCategoryModel model = new AdminCategoryModel();
            List<CategoryLanguageModel> CategoryLanguages = new List<CategoryLanguageModel>();
            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                Language = Language.English,
                LanguageName = Language.English.ToString(),
            });

            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                Language = Language.Arbic,
                LanguageName = Language.Arbic.ToString(),
            });

            model.Categorylanguagemodellist = CategoryLanguages;
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseIconCategory != null)
                {
                    Stream inStream = model.FileBaseIconCategory.InputStream;
                    Image PostedImage = Image.FromStream(inStream);

                    string ogFileName = model.FileBaseIconCategory.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseIconCategory.SaveAs(Path.Combine(GlobalConfig.CategoryIconPath, thisFileName));
                    model.IconName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");

            }
            return View("AddorUpdate", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            AdminCategoryModel model = await _service.GetCategoryDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseIconCategory != null)
                {
                    Stream inStream = model.FileBaseIconCategory.InputStream;
                    Image PostedImage = Image.FromStream(inStream);

                    string ogFileName = model.FileBaseIconCategory.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseIconCategory.SaveAs(Path.Combine(GlobalConfig.CategoryIconPath, thisFileName));
                    model.IconName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            mResult = await _service.DeleteCategory(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CheckExistingTitle()
        {
            bool IsExist = true;

            if (Request.Form[0] != null)
            {
                string Name = Request.Form[0];
                long CategoryId = Convert.ToInt64(Request.Form[1]);
                IsExist = _service.IsTitleExist(Name, CategoryId);
            }

            return Json(!IsExist);
        }
    }
}

Songy.Admin/Controllers/SubCategoryController.cs
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class SubCategoryController : ApplicationBaseController
    {
        private SubCategoryService _service;

        public SubCategoryController()
        {
            _service = new SubCategoryService();
        }

        public ActionResult Index()
        {
            IQueryable<SubCategoryListModel> objCategories = _service.GetAllSubCategory_IQueryable();
            return View(objCategories);
        }

        public ActionResult Add()
        {
            SubCategoryAddUpdateRequestModel model = new SubCategoryAddUpdateRequestModel();
            List<SubCategoryLanguageModel> SubCategoryLanguages = new List<SubCategoryLanguageModel>();
            SubCategoryLanguages.Add(new SubCategoryLanguageModel()
            {
                Language = Language.English,
                LanguageName = Language.English.ToString(),
            });

            SubCategoryLanguages.Add(new SubCategoryLanguageModel()
            {
                Language = Language.Arbic,
                LanguageName = Language.Arbic.ToString(),
            });
         
            model.Languages = SubCategoryLanguages;
            BindCategory(false);
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(SubCategoryAddUpdateRequestModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseModel<SubCategoryAddUpdateResultModel> mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            BindCategory(false);
            return View("AddorUpdate", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            SubCategoryAddUpdateRequestModel model = await _service.GetSubCategoryDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            BindCategory(false);
            return View("AddorUpdate", model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(SubCategoryAddUpdateRequestModel model)
        {
            if (ModelState.IsValid)
            {
                ResponseModel<SubCategoryAddUpdateResultModel> mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");

            }
            BindCategory(false);
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            ResponseModel<object> mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CheckExistingName()
        {
            bool IsExist = true;

            if (Request.Form[0] != null && Request.Form[1] != null && Request.Form[2] != null)
            {
                string Name = Request.Form[0];
                int CategoryId = Convert.ToInt32(Request.Form[1]);
                int SubCategoryId = Convert.ToInt32(Request.Form[2]);
                IsExist = _service.IsNameExist(Name, CategoryId, SubCategoryId);
            }

            return Json(!IsExist);
        }
    }
}

Songy.Admin/Views/SubCategory/AddorUpdate.cshtml
@model SubCategoryAddUpdateRequestModel
@{
    string Action = ViewBag.Action;
    ViewBag.Title = "AddorUpdate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/select2")
@Styles.Render("~/css/wizard")
<section>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">@Action Sub category</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    @using (Html.BeginForm(Action, "SubCategory", FormMethod.Post, new
                    {
                        @id = "submitForm",
                        @class = "wizard-circle"
                    }))
                    {
                        if (Model != null && Model.Id > 0)
                        {
                            @Html.HiddenFor(x => x.Id)
                        }
                        <h6>Basic</h6>
                        <fieldset>
                            <div class="form-group row">
                                <div class="col-md-3" style="text-align:right;">
                                    <label>
                                        Category <span class="red">*</span>
                                    </label>
                                </div>
                                <div class="col-md-5">
                                    @Html.DropDownListFor(x => x.CategoryId, new SelectList(ViewData["CategoryList"] as IEnumerable<SelectListItem>, "Value", "Text"), "Select Category", new { @class = "select2 form-control required" })
                                    @Html.ValidationMessageFor(x => x.CategoryId)
                                </div>
                            </div>
                        </fieldset>

                        for (int i = 0; i < Model.Languages.Count; i++)
                        {
                            @Html.HiddenFor(x => x.Languages[i].Language)
                            @Html.HiddenFor(x => x.Languages[i].SubCategoryId)
                            @Html.HiddenFor(x => x.Languages[i].CategoryId, new { @class = "category", Value = Model.CategoryId })
                            <h6>@Model.Languages[i].LanguageName</h6>
                            <fieldset>
                                <div class="form-group row">
                                    <div class="col-md-3" style="text-align:right;">
                                        <label> Sub Category Name  <span class="red">*</span></label>
                                    </div>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(x => x.Languages[i].Name, new { @class = "form-control required" })
                                        @Html.ValidationMessageFor(x => x.Languages[i].Name)
                                    </div>
                                </div>
                            </fieldset>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    @Scripts.Render("~/jQuery/select2")
    <script type="text/javascript">
        ActiveMenu("SubCategory")
        $(document).ready(function (e) {
            $('.select2').select2({

            });
            $(".category").val($("#CategoryId").val());
            console.log($(".category").val());

            $("#CategoryId").change(function () {
                $(".category").val($("#CategoryId").val());
                console.log($(".category").val());
            });
        });
    </script>
}

Songy.Admin/Views/SubCategory/Index.cshtml
@model IQueryable<SubCategoryListModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

<link rel="stylesheet" href="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.css")" />

@using (Html.BeginForm("DeleteCategory", "Category", FormMethod.Post, new { @class = "form-horizontal form-simple", @id = "frmDelete" }))
{
    @Html.Hidden("CategoryId")
}

@helper ActionButtons(long SubCategoryId)
{
    /**/
    <div class="form-group row">
        <a href="@Url.Action("Edit", "SubCategory", new { @id = SubCategoryId})" class="btn btn-sm btn-primary btn-blue">
            <i class="icon-edit2"></i> Edit
        </a>
        <a href="javascript:;" class="btn btn-sm btn-danger btnDelete" data-id="@SubCategoryId">
            <i class="icon-trash4"></i> Delete
        </a>
    </div>
}
@helper SubCategoryLanguageList(List<SubCategoryLanguageList> model)
{
    /**/
    <ul>
        @foreach (var item in model)
        {
            <li>
                <i class="fa fa-caret-right"></i>
                @item.LanguageName :- @Html.Raw(item.Name)
            </li>
        }
    </ul>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card box-shadow-0 border-primary">
                <div class="card-header card-head-inverse bg-primary">
                    <h4 class="card-title">All Sub Category</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4 white font-size-large"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2 white font-size-large"></i></a></li>
                            <li class="btn btn-white">
                                <a href="@Url.Action("Add")" class="primary">
                                    <i class="icon-plus3 primary"></i>&nbsp;Add New
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {

                               column.Add()
                              .Titled("Category Name")
                              .Encoded(false)
                              .Sanitized(false)
                              .RenderValueAs(x => x.CategoryName.ToString());

                               column.Add()
                               .Titled("Sub Category Name")
                               .Encoded(false)
                               .Sanitized(false)
                               .RenderValueAs(x => SubCategoryLanguageList(x.Languages));

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.Id));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("SubCategory")
        $(".jsgrid-grid-body").css('overflow-x', 'auto');
          $(function () {
              $(".btnDelete").click(function () {
                deleteRow($(this), '@Url.Action("Delete")');
            });
        });

    </script>
}