Songy.Admin/Controllers/ContactUsController.cs
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly ContactusService _service;

        public ContactUsController()
        {
            _service = new ContactusService();
        }
        public ActionResult Index()
        {
            IQueryable<ContactUsViewModel> objData = _service.getContactUs_IQueryable();
            return View(objData);
        }
    }
}

Songy.Admin/Controllers/HomeController.cs
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly UtilityService _service;
        public HomeController()
        {

            _service = new UtilityService();
        }
        public async Task<ActionResult> Index()
        {
            AdminDashboardModel model = await _service.GetAddminDashboard();
            return View(model);
        }

    }
}

Songy.Admin/Controllers/RequestedSongController.cs
using Microsoft.AspNet.Identity;
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class RequestedSongController : ApplicationBaseController
    {
        private RequestedSongService _service;

        ResponseModel<object> mResult;
        public RequestedSongController()
        {
            _service = new RequestedSongService();
        }

        public ActionResult Pending()
        {
            ViewBag.Title = "Pending";
            IQueryable<SongsViewModel> objSongs = _service.GetIQueryablePendingSongs();
            return View("Index", objSongs);
        }

        public ActionResult RequestedBySongs(long Id)
        {
            IQueryable<SongsViewModel> objSongs = _service.RequestedBySongs(Id);
            ViewBag.Title = objSongs.FirstOrDefault()?.Title;
            return View("Index", objSongs);
        }
        public ActionResult RequestedSongsDownloadByUser(long Id)
        {
            IQueryable<UserDetailsModel> objUser = _service.RequestedSongsDownloadByUser(Id);
            ViewBag.Title = objUser.FirstOrDefault()?.Title;
            return View(objUser);
        }

        public ActionResult Uploaded()
        {
            ViewBag.Title = "Uploaded";
            IQueryable<SongsViewModel> objSongs = _service.GetIQueryableUploadedSongs();
            return View("Index", objSongs);
        }

        public async Task<ActionResult> Add(long Id)
        {
            BindCategory();
            BindLanguage();
            RequestedSongsAddUpdateModel model = await _service.GetRequestedSongsDetail(Id);
            if (model == null)
                return RedirectToActionPermanent("Pending");
            return View("AddorUpdate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(RequestedSongsAddUpdateModel model)
        {
            BindCategory();
            BindLanguage();
            if (ModelState.IsValid)
            {
                if (model.FileBaseSongs != null)
                {
                    string ogFileName = model.FileBaseSongs.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseSongs.SaveAs(Path.Combine(GlobalConfig.RequestedSongsPath, thisFileName));
                    model.FileName = thisFileName;
                }
                model.UserId = User.Identity.GetUserId();
                mResult = await _service.InsertOrUpdateRequestedSongs(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Uploaded");

            }
            return View("AddorUpdate", model);
        }
    }
}

Songy.Admin/Controllers/SongsController.cs
using Microsoft.AspNet.Identity;
using Songy.Core.Enumerations;
using Songy.Core.Helper;
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class SongsController : ApplicationBaseController
    {
        private SongsService _service;

        ResponseModel<object> mResult;

        public SongsController()
        {
            _service = new SongsService();
        }

        public ActionResult Index()
        {
            IQueryable<SongsViewModel> objSongs = _service.GetIQueryableSongs();
            return View(objSongs);
        }

        public async Task<ActionResult> Add()
        {
            SongsAddUpdateModel model = new SongsAddUpdateModel();
            BindList();
            return View("AddorUpdate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(SongsAddUpdateModel model)
        {
          
            if (ModelState.IsValid)
            {
                if (model.FileBaseSongs != null)
                {
                    string ogFileName = model.FileBaseSongs.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseSongs.SaveAs(Path.Combine(GlobalConfig.SongsPath, thisFileName));
                    model.FileName = thisFileName;
                }
                model.UserId = User.Identity.GetUserId();
                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");

            }
            BindList();
            return View("AddorUpdate", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            SongsAddUpdateModel mResult = await _service.GetSongsDetail(id);
            BindList(mResult.CategoryId);
            if (mResult == null)
                return RedirectToActionPermanent("Index");
            return View("AddorUpdate", mResult);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(SongsAddUpdateModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.FileBaseSongs != null)
                {
                    string ogFileName = model.FileBaseSongs.FileName.Trim('\"');
                    string shortGuid = ShortGuid.NewGuid().ToString();
                    var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                    model.FileBaseSongs.SaveAs(Path.Combine(GlobalConfig.SongsPath, thisFileName));
                    model.FileName = thisFileName;
                }

                mResult = await _service.AddUpdate(model);
                OnBindMessage(mResult.Status, mResult.Message);

                if (mResult.Status == ResponseStatus.Success)
                    return RedirectToActionPermanent("Index");
            }
            BindList();
            return View("AddorUpdate", model);
        }

        public async Task<JsonResult> Delete(long Id)
        {
            mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSubCategory(int CategoryId)
        {

            using (SubCategoryService service = new SubCategoryService())
            {
                List<SubCategoryDropdownModel> Subcategories = (from x in service.GetSubCategoryDropdown(CategoryId)
                                                                select new SubCategoryDropdownModel
                                                                {
                                                                    Id = x.Id,
                                                                    Name = x.Name
                                                                }).ToList();
                return Json(Subcategories, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Songy.Admin/Controllers/UserController.cs
using Songy.Core.Model;
using Songy.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Songy.Admin.Controllers
{
    public class UserController : Controller
    {

        private UserService _service;
        public UserController()
        {
            _service = new UserService();
        }

        public ActionResult Index()
        {
            return View(_service.getAllUsers_IQueryable());
        }

        [HttpPost]
        public JsonResult ActiveToggle(string Id)
        {
            ResponseModel<bool> mResult = _service.ActiveToggle(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(string Id)
        {
            ResponseModel<object> mResult = await _service.Delete(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> ForgotPasswordByAdmin(string Id)
        {
            ResponseModel<object> mResult = await _service.ForgotPasswordByAdmin(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Songy.Admin/Views/Home/Index.cshtml
@model AdminDashboardModel
@{
    ViewBag.Title = "Home Page";
}
<div class="row">
    <div class="col-xl-4 col-lg-6 col-xs-12">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="p-2 text-xs-center bg-deep-orange media-left media-middle">
                        <i class="icon-users3 font-large-2 white"></i>
                    </div>
                    <div class="p-2 media-body">
                        <a href="@Url.Action("Index","User")">
                            <h5 class="text-bold-600 text-primary">@Model.TotalUser</h5>
                            <h5>Total User</h5>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-lg-6 col-xs-12">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="p-2 text-xs-center bg-pink media-left media-middle">
                        <i class="icon-music font-large-2 white"></i>
                    </div>
                    <div class="p-2 media-body">
                        <a href="@Url.Action("Index","Songs")">
                            <h5 class="text-bold-600 cyan">@(Model.TotalSongs)</h5>
                            <h5>Total Songs</h5>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-xs-12">
        <div class="card">
            <div class="card-body">
                <div class="media">
                    <div class="p-2 text-xs-center bg-teal media-left media-middle">
                        <i class="icon-ios-contact font-large-2 white"></i>
                    </div>
                    <div class="p-2 media-body">
                        <a href="@Url.Action("Index","ContactUs")">
                            <h5 class="text-bold-600 cyan">@(Model.TotalInquiry)</h5>
                            <h5>Total Inquiry</h5>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="card">
            <div class="card-body">
                <div class="card-block">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 col-sm-12 border-right-blue-grey border-right-lighten-5">
                            <div class="p-1 text-xs-center">
                                <div>
                                    <h3 class="font-large-1 success darken-1 text-bold-400">
                                        @(Model.TotalSongs)
                                    </h3>
                                    <span class="font-medium-2 grey darken-1">Total Songs</span>
                                </div>
                                <hr />
                                <div class="card-body overflow-hidden">
                                    <ul class="list-inline clearfix mb-0">
                                        <li class="col-md-4 border-right-grey border-right-lighten-2 pr-2">
                                            <h3 class="success text-bold-400">@(Model.TotalRequest.ToString())</h3>
                                            <span class="font-medium-1 grey darken-1">Request</span>
                                        </li>
                                        <li class="col-md-4 border-right-grey border-right-lighten-2 pr-2">
                                            <h3 class="success text-bold-400">@(Model.TotalPurchase.ToString())</h3>
                                            <span class="font-medium-1 grey darken-1">Purchase</span>
                                        </li>
                                        <li class="col-md-4">
                                            <h3 class="success text-bold-400">@(Model.TotalDownload.ToString())</h3>
                                            <span class="font-medium-1 grey darken-1">Download</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 col-sm-12 border-right-blue-grey border-right-lighten-5">
                            <div class="p-1 text-xs-center">
                                <div>
                                    <h3 class="font-large-1 success darken-1 text-bold-400">
                                        @(Model.TotalRequest)
                                    </h3>
                                    <span class="font-medium-2 grey darken-1">Total Requested Songs</span>
                                </div>
                                <hr />
                                <div class="card-body overflow-hidden">
                                    <ul class="list-inline clearfix mb-0">

                                        <li class="col-md-6 border-right-grey border-right-lighten-2 pr-2">
                                            <a href="@Url.Action("Uploaded","RequestedSong")">
                                                <h3 class="success text-bold-400">@(Model.TotalUpload.ToString())</h3>
                                                <span class="font-medium-1 grey darken-1">Uploaded</span>
                                            </a>
                                        </li>
                                        <li class="col-md-6 border-right-grey border-right-lighten-2 pr-2">
                                            <a href="@Url.Action("Pending","RequestedSong")">
                                                <h3 class="success text-bold-400">@(Model.TotalPending.ToString())</h3>
                                                <span class="font-medium-1 grey darken-1">Pending</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>